### PR TITLE
Add support to Gnome 45

### LINKED ISSUE #16: Gnome 45 not work
Not word in gnome 45.

Any solution?

Tanks.

### PR DESCRIPTION
**Pull request by brunodrugowick**
Based on https://gjs.guide/extensions/upgrading/gnome-shell-45.html.

Closes #16

### CODE REVIEW

**Comment by sagitariozod** [comment]
It doesn't work, it gives the following error.

unexpected token: identifier

Thank you anyway.

**Comment by justOtto** [comment]
Same here, "unexpected token: identifier"
Think it's just a small thing but i can't find it.

**Comment by brunodrugowick** [comment]
I thought the latest version on the Gnome Extensions website fixed the error.

**Comment by brunodrugowick** [comment]
Which OS are you using? Gonna make a VM and test it on the same system.

**Comment by justOtto** [comment]
No, i installed from the extensions website and still get this error. Should be the same code as here on github.
The code looks quite uncomplicated but i can't figure out what is wrong.
Screenshot from 2023-10-13 18-21-10

**Comment by justOtto** [comment]
I'm using Arch, it was Antergos before ... i'll try it on my notebook too but all i have is Arch based, Endeavour in this case.
Does it work on your System? What are you using?

**Comment by brunodrugowick** [comment]
I don't have anything with Gnome 45. I'm on PopOS on most setups and also Ubuntu 22.04. All works fine.

I'll take a look later this weekend on something with Gnome 45 on a VM.

**Comment by justOtto** [comment]
Ok, thanks in advance!

**Comment by brunodrugowick** [comment]
The problem is in line 9, where it gets the current banner position. It might have something to do with some changes in the API, this might not be a valid call anymore (or property, whatever). 

I'll dig a little in the Gnome source code to understand how to fix.

**Comment by brunodrugowick** [comment]
I'll track this on #19 from now on.

**Comment by justOtto** [comment]
I'm a bit late, but thank you for your work! Good to have the notifications back on the right place.

**Pull request merged**
